import "ViewModel/MainViewModel.idl";


namespace RedDotScanner
{
    [default_interface]
    runtimeclass SetupView : Microsoft.UI.Xaml.Controls.UserControl
    {
        SetupView();

        MainViewModel ViewModel { get; set; };
    }
}
